url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/portafolio-prueba" # the subpath of your site, e.g. /blog
title: "portafolio" # the name of your site, e.g. ACME Corp.
lang: "es-CL"